name: Issue and PR automation
description: Automates issue and pull request management
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
